import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from Santa Claus" });
  const { data: sessionData } = useSession();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Secret Santa 🎅</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Secret <span className="text-[hsl(280,100%,70%)]">Santa</span> App 🎅
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="new-group"
              onClick={(e) => {
                e.preventDefault();
                if (!sessionData) {
                  alert("You need to be logged in to create a group");
                  return;
                } else {
                  router.push("new-group");
                }
              }}
            >
              <h3 className="text-2xl font-bold">Create group →</h3>
              <div className="text-lg">
                Create your Secret Santa Group - Enjoy the holidays by creating
                a group to do the Secret Santa with
                your friends and family.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="my-groups"
              onClick={(e) => {
                e.preventDefault();
                if (!sessionData) {
                  alert("You need to be logged in to create a group");
                  return;
                } else {
                  router.push("my-groups");
                }
              }}
            >
              <h3 className="text-2xl font-bold">My Secret Santas →</h3>
              <div className="text-lg">
                View your Secret Santas - View your Secret Santas and see who you
                are giving a gift to and who is giving you a gift (secret).
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
